task_management/api/urls.py
from django.urls import path, include
from .views import ProjectListAPIView, ProjectDetailAPIView, TaskListAPIView, TaskDetailAPIView, api_home

urlpatterns = [
    path('', api_home, name='api_home'),
    path('projects/', ProjectListAPIView.as_view(), name='project-list'),
    path('projects/<int:pk>/', ProjectDetailAPIView.as_view(), name='project-detail'),
    path('tasks/', TaskListAPIView.as_view(), name='task-list'),
    path('tasks/<int:pk>/', TaskDetailAPIView.as_view(), name='task-detail'),
]

task_management/project_task/urls.py
from django.urls import path, include
from .views import (
    TaskListView, TaskCreateView, TaskDeleteView, TaskUpdateView, task_detail, ProjectListView, ProjectCreateView, ProjectDeleteView,
    project_detail, project_task_list
)

urlpatterns = [
    # Task URLs
    path('tasks/', TaskListView.as_view(), name='task_list'),
    path('tasks/create/', TaskCreateView.as_view(), name='task_create'),
    path('tasks/<int:pk>/delete/', TaskDeleteView.as_view(), name='task_delete'),
    path('tasks/<int:pk>/update/', TaskUpdateView.as_view(), name='task_update'),
    path('tasks/<int:pk>/', task_detail, name='task_detail'),

    # Project URLs
    path('projects/', ProjectListView.as_view(), name='project_list'),
    path('projects/create/', ProjectCreateView.as_view(), name='project_create'),
    path('projects/<int:pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),
    path('projects/<int:pk>/', project_detail, name='project_detail'),
    path('projects/<int:pk>/tasks/', project_task_list, name='project_task_list'),

    #api
     path('', include('api.urls')),
]

task_management/task_management/urls.py
from django.contrib import admin
from django.urls import path, include
from project_task.views import homeView, custom_404_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homeView, name='home'),
    path('', include('project_task.urls')), 
    path('api/', include('api.urls')),
]

handler404 = 'project_task.views.custom_404_view'

task_management/api/models.py
from django.db import models

# Create your models here.

task_management/project_task/models.py
# task_manager/models.py
from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError

class Client(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
    
class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, default='No Description Given')
    client = models.ForeignKey('Client', on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    
    def clean(self):
        super().clean()
        if self.start_date and self.start_date > timezone.now().date():
            raise ValidationError("Start date cannot be in the future.")
        if self.start_date and self.end_date and self.start_date > self.end_date:
            raise ValidationError("End date cannot be before start date.")
        
    def __str__(self):
        return self.name

class Task(models.Model):
    STATUS_CHOICES = [
        ('TODO', 'To Do'),
        ('WIP', 'Work In Progress'),
        ('ONHOLD', 'On Hold'),
        ('DONE', 'Done'),
    ]

    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, default='No Description Given')
    project = models.ForeignKey('Project', on_delete=models.CASCADE, related_name='task')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='No Status Available')
    
    def __str__(self):
        return self.name

task_management/api/views.py
from django.shortcuts import render
from rest_framework import generics
from project_task.models import Project, Task
from .serializers import ProjectListSerializer, ProjectDetailSerializer, TaskSerializer
from rest_framework.pagination import PageNumberPagination

def api_home(request):
    return render(request, 'project_task/api_home.html')

class FiveItemsPerPagePagination(PageNumberPagination):
    page_size = 2
    page_size_query_param = 'page_size'
    max_page_size = 100
    
class ProjectListAPIView(generics.ListCreateAPIView):
    queryset = Project.objects.all()
    serializer_class = ProjectListSerializer
    pagination_class = FiveItemsPerPagePagination

class ProjectDetailAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Project.objects.all()
    serializer_class = ProjectDetailSerializer

class TaskListAPIView(generics.ListCreateAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer
    pagination_class = FiveItemsPerPagePagination

class TaskDetailAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer

task_management/project_task/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.http import HttpResponseNotFound
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView
from .models import Project, Task, Client
from django.urls import reverse_lazy
from django.utils import timezone

def custom_404_view(request, exception):
    return HttpResponseNotFound('<h1>Page not found</h1>')

def homeView(request):
    return render(request, 'project_task/home.html')

class TaskListView(ListView):
    model = Task
    template_name = 'project_task/task_list.html'

class TaskCreateView(CreateView):
    model = Task
    fields = ['name', 'description', 'project', 'status']
    template_name = 'project_task/task_form.html'
    success_url = reverse_lazy('task_list')

class TaskDeleteView(DeleteView):
    model = Task
    success_url = reverse_lazy('task_list')

class TaskUpdateView(UpdateView):
    model = Task
    fields = ['status']    #field to edit
    template_name = 'project_task/task_status.html'
    success_url = reverse_lazy('task_list')

def task_detail(request, pk):
    try:
        task = Task.objects.get(pk=pk)
    except Task.DoesNotExist:
        return HttpResponse('No task with the given id', status=404)
    
    context = {'task': task}
    return render(request, 'project_task/task_detail.html', context)

class ProjectListView(ListView):
    model = Project
    template_name = 'project_task/project_list.html'
    
    #modifying queryset to get project which are not ended (end date having future date)
    def get_queryset(self):
        return Project.objects.filter(end_date__gte=timezone.now())

class ProjectCreateView(CreateView):
    model = Project
    fields = ['name', 'description', 'client', 'start_date', 'end_date']
    template_name = 'project_task/project_form.html'
    success_url = reverse_lazy('project_list')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['clients'] = Client.objects.all()  # Add clients queryset to the context
        return context

class ProjectDeleteView(DeleteView):
    model = Project
    success_url = reverse_lazy('project_list')

def project_detail(request, pk):
    try:
        project = Project.objects.get(pk=pk)
    except Project.DoesNotExist:
        return HttpResponse('No project with the given id', status=404)
    
    context = {'project': project}
    return render(request, 'project_task/project_detail.html', context)

def project_task_list(request, pk):
    try:
        project = Project.objects.get(pk=pk)
    except Project.DoesNotExist:
        return HttpResponse('No project with the given id', status=404)
    
    tasks = Task.objects.filter(project=project)
    if not tasks:
        tasks = None
    context = {
        'project': project,
        'tasks': tasks,
    }
    return render(request, 'project_task/project_task_list.html', context)

task_management/project_task/templates/project_task/api_home.html
{% extends 'project_task/base.html' %}

{% block title %}Api Home{% endblock %}

{% block content %}
<h1>Weclome to API page</h1>
<table>
    <tr>
        <th>Routes</th>
        <th>Usage</th>
    </tr>
    <tr>
        <td><a href="{% url 'project-list' %}" class="btn" target="_blank">Project List</a></td>
        <td>GET all projects</td>
    </tr>
    <tr>
        <td><a href="{% url 'project-detail' pk=1 %}" class="btn" target="_blank">Project Detail</a></td>
        <td>GET/DELETE/PUT Project(default pk=1)</td>
    </tr>
    <tr>
        <td><a href="{% url 'task-list' %}" class="btn" target="_blank">Task List</a></td>
        <td>GET all tasks</td>
    </tr>
    <tr>
        <td><a href="{% url 'task-detail' pk=1 %}" class="btn" target="_blank">Task Detail</a></td>
        <td>GET/DELETE/PUT Task (default pk=1)</td>
    </tr>
</table>
{% endblock %}

task_management/project_task/templates/project_task/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'project_task/base.css' %}">
    <title>{% block title %}Task Management System{% endblock %}</title>
</head>
<body>
    <header>
          <ul class="navbar">
            <li><a class="active" href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'task_list' %}">All Tasks</a></li>
            <li><a href="{% url 'project_list' %}">All Projects</a></li>
            <li><a href="{% url 'api_home' %}">Api Routes</a></li>
          </ul>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>
   
</body>
</html>

task_management/project_task/templates/project_task/home.html
{% extends 'project_task/base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}
<h1>Weclome to task management app :\</h1>
<h2>Navigate from navbar link for more details..</h2>
{% endblock %}

task_management/project_task/templates/project_task/project_confirm_delete.html
<!-- Project delete confirmation  -->
{% extends 'project_task/base.html' %}

{% block title %}Confirm delete{% endblock %}

{% block content %}
  <h2>Confirm Deletion</h2>
  <p>Are you sure you want to delete the project "{{ object }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button  class="btn-edit"  type="submit">Confirm Delete</button>
    <a class="btn-delete" href="{% url 'project_list' %}">Cancel</a>
  </form>
{% endblock %}

task_management/project_task/templates/project_task/project_detail.html
<!-- single project detail view with task listed in table -->

{% extends 'project_task/base.html' %}

{% block title %}Project Detail{% endblock %}

{% block content %}
<div class="container">
  <h2 class="project-name">{{ project.name }}</h2>
  <p class="description">Description: {{ project.description }}</p>
  <p class="client">Client: {{ project.client }}</p>
  <p class="end-date">Start Date: {{ project.start_date }}</p>
  <p class="end-date">End Date: {{ project.end_date }}</p>
  {% if project.task.exists %}
  <h3 class="tasks-heading">Tasks</h3>
    <table class="task-table">
      <thead>
        <tr>
          <th>Task Name</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        {% for task in project.task.all %}
          <tr>
            <td>{{ task.name }}</td>
            <td>{{ task.status }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <p>No tasks for this project</p>
    {% endif %}
    <a class="btn-create" href="{% url 'project_task_list' pk=project.pk %}">View Task List</a>
</div>

{% endblock %}

task_management/project_task/templates/project_task/project_form.html
<!-- form to create new project -->
{% extends 'project_task/base.html' %}

{% block title %}Project Form{% endblock %}

{% block content %}
<div class="project-container">
  <h2>Create New Project</h2>
  <form method="post" class="project-form">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_name">Name:</label>
      <input type="text" id="id_name" name="name" class="form-control">
      {% if form.name.errors %}
        <div class="text-danger">
          {% for error in form.name.errors %}
            {{ error }}
          {% endfor %}
        </div>
      {% endif %}
    </div>
    <div class="form-group">
      <label for="id_description">Description:</label>
      <textarea id="id_description" name="description" class="form-control"></textarea>
    </div>
    <div class="form-group">
      <label for="id_client">Client:</label><br>
      <select id="id_client" name="client" class="form-control">
        {% for client in clients %}
          <option value="{{ client.id }}">{{ client.name }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="form-group">
      <label for="id_start_date">Start Date:</label>
      <input type="date" id="id_start_date" name="start_date" class="form-control">
      <p><b>Future start-date</b> won't accepted</p>
      {% if form.start_date.errors %}
        <div class="text-danger">
          {% for error in form.start_date.errors %}
            {{ error }}
          {% endfor %}
        </div>
      {% endif %}
    </div>
    <div class="form-group">
      <label for="id_end_date">End Date:</label>
      <input type="date" id="id_end_date" name="end_date" class="form-control" value="{{ form.end_date.value|default_if_none:''|date:'Y-m-d' }}"> 
      {% if form.end_date.errors %}
        <div class="text-danger">
          {% for error in form.end_date.errors %}
            {{ error }}
          {% endfor %}
        </div>
      {% endif %}
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
</div>
{% endblock %}

task_management/project_task/templates/project_task/project_list.html
<!-- listing all the projects -->
{% extends 'project_task/base.html' %}

{% block title %}Project List{% endblock %}

{% block content %}
<h2>Projects Which are not Ended</h2>
<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Client</th>
      <th>Actions</th>
      <th>End Date</th>
    </tr>
  </thead>
  <tbody>
    {% for project in object_list %}
    <tr>
      <td>{{ project.name }}</td>
      <td>{{ project.client }}</td>
      <td>
        <a class="btn-view" href="{% url 'project_detail' project.pk %}">View</a>
        <a class="btn-delete" href="{% url 'project_delete' project.pk %}">Delete</a>
      </td>
      <td>{{ project.end_date }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<a class="btn-create" href="{% url 'project_create' %}">Create New Project</a>

{% endblock %}

task_management/project_task/templates/project_task/project_task_list.html
<!-- individual project with list of tasks -->

{% extends 'project_task/base.html' %}

{% block title %}Project with tasks{% endblock %}

{% block content %}
<h2>Tasks for Project: {{ project.name }}</h2>
<ul>
  {% if tasks is not None %}
    {% for task in tasks %}
      <li>{{ task.name }} - {{ task.status }}</li><br>
    {% endfor %}
  {% else %}
  <li>No tasks for this project</li>
  {% endif %}
</ul>
{% endblock %}

task_management/project_task/templates/project_task/task_confirm_delete.html
<!-- task delete confirmation -->
{% extends 'project_task/base.html' %}

{% block title %}Confirm task deletion{% endblock %}

{% block content %}
  <h2>Confirm Deletion</h2>
  <p>Are you sure you want to delete the task "{{ object }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button class="btn-edit" type="submit">Confirm Delete</button>
    <a class="btn-delete" href="{% url 'task_list' %}">Cancel</a>
  </form>
{% endblock %}

task_management/project_task/templates/project_task/task_detail.html
<!-- task detail view -->
{% extends 'project_task/base.html' %}

{% block title %}Task Detail{% endblock %}

{% block content %}
<div class="container">
  <h2 class="project-name">{{ task.name }}</h2>
  <p class="description">Description: {{ task.description }}</p>
  <p class="client">Project: {{ task.project }}</p>
  <p class="client">Status: {{ task.status }}</p>
</div>
{% endblock %}

task_management/project_task/templates/project_task/task_form.html
<!-- task creation form -->
{% extends 'project_task/base.html' %}

{% block title %}Task Form{% endblock %}

{% block content %}
<div class="task-container">
  <h2>Create New Task</h2>
  <form method="post" class="task-form">
    {% csrf_token %}
    <div class="form-group">
      {% for field in form %}
        {{ field.errors }}
        {{ field.label_tag }}
        {{ field }}
      {% endfor %}
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
</div>
{% endblock %}

task_management/project_task/templates/project_task/task_list.html
<!-- list of tasks with feture to edit, delete, view -->
{% extends 'project_task/base.html' %}

{% block title %}Task List{% endblock %}

{% block content %}
<h2>All Tasks</h2>
<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>Status</th>
      <th>Project</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for task in object_list %}
    <tr>
      <td>{{ task.name }}</td>
      <td>{{ task.status }}</td>
      <td>{{ task.project.name }}</td>
      <td>
        <a class="btn-edit" href="{% url 'task_update' task.pk %}">Change Status</a>
        <a class="btn-delete" href="{% url 'task_delete' task.pk %}">Delete</a>
        <a class="btn-view" href="{% url 'task_detail' task.pk %}">View</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<a class="btn-create" href="{% url 'task_create' %}">Create New Task</a>
{% endblock %}

task_management/project_task/templates/project_task/task_status.html
<!-- task status edit page -->
{% extends 'project_task/base.html' %}

{% block title %}Task Status{% endblock %}

{% block content %}
  <h2>Edit Task Status</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
{% endblock %}